Catch and throws BadRequestHttpException in ShortUrlController
gomeeki/url-shortener-bundle pull request #5
Opened 2016-09-21 08:32 UTC by wallsfantasy

2016-09-21 09:52 UTC, AlexStansfield commented on Controller/ShortUrlController.php
> +     * @return JsonResponse|BadRequestHttpException
It throws the exception rather than returns it, you'll need to add `@throws` and put the exception there.

2016-09-21 09:53 UTC, AlexStansfield commented on Controller/ShortUrlController.php
> +        /** @var ShortUrlEntityFactory $shortUrlFactory */
Should this be the Interface rather than concrete class?

2016-09-21 09:54 UTC, AlexStansfield requested changes
Great work. Some minor docblock stuff

2016-09-22 10:34 UTC, wallsfantasy commented
@AlexStansfield done~*

2016-09-22 10:46 UTC, AlexStansfield approved these changes

2016-09-22 10:47 UTC, merged